
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var a;a||(a=typeof Module !== 'undefined' ? Module : {});var m,n;a.ready=new Promise(function(b,c){m=b;n=c});var t=Object.assign({},a),u=[],x="./this.program",y=(b,c)=>{throw c;},z="object"==typeof window,A="function"==typeof importScripts,B="",C,D,E,fs,F,G;
if("object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node)B=A?require("path").dirname(B)+"/":__dirname+"/",G=()=>{F||(fs=require("fs"),F=require("path"))},C=function(b,c){G();b=F.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")},E=b=>{b=C(b,!0);b.buffer||(b=new Uint8Array(b));return b},D=(b,c,d)=>{G();b=F.normalize(b);fs.readFile(b,function(e,f){e?d(e):c(f.buffer)})},1<process.argv.length&&(x=process.argv[1].replace(/\\/g,"/")),u=process.argv.slice(2),
process.on("uncaughtException",function(b){if(!(b instanceof H))throw b;}),process.on("unhandledRejection",function(b){throw b;}),y=(b,c)=>{if(noExitRuntime||0<I)throw process.exitCode=b,c;c instanceof H||J("exiting due to exception: "+c);process.exit(b)},a.inspect=function(){return"[Emscripten Module object]"};else if(z||A)A?B=self.location.href:"undefined"!=typeof document&&document.currentScript&&(B=document.currentScript.src),_scriptDir&&(B=_scriptDir),0!==B.indexOf("blob:")?B=B.substr(0,B.replace(/[?#].*/,
"").lastIndexOf("/")+1):B="",C=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},A&&(E=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),D=(b,c,d)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};a.print||console.log.bind(console);var J=a.printErr||console.warn.bind(console);
Object.assign(a,t);t=null;a.arguments&&(u=a.arguments);a.thisProgram&&(x=a.thisProgram);a.quit&&(y=a.quit);var K;a.wasmBinary&&(K=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&L("no native wasm support detected");var aa,M=!1;
function ba(b,c,d,e){var f={string:function(h){var k=0;if(null!==h&&void 0!==h&&0!==h){var r=(h.length<<2)+1;k=N(r);ca(h,O,k,r)}return k},array:function(h){var k=N(h.length);P.set(h,k);return k}};b=a["_"+b];var g=[],p=0;if(e)for(var q=0;q<e.length;q++){var v=f[d[q]];v?(0===p&&(p=da()),g[q]=v(e[q])):g[q]=e[q]}d=b.apply(null,g);return d=function(h){0!==p&&ea(p);if("string"===c)if(h){for(var k=O,r=h+NaN,w=h;k[w]&&!(w>=r);)++w;if(16<w-h&&k.subarray&&ha)h=ha.decode(k.subarray(h,w));else{for(r="";h<w;){var l=
k[h++];if(l&128){var S=k[h++]&63;if(192==(l&224))r+=String.fromCharCode((l&31)<<6|S);else{var fa=k[h++]&63;l=224==(l&240)?(l&15)<<12|S<<6|fa:(l&7)<<18|S<<12|fa<<6|k[h++]&63;65536>l?r+=String.fromCharCode(l):(l-=65536,r+=String.fromCharCode(55296|l>>10,56320|l&1023))}}else r+=String.fromCharCode(l)}h=r}}else h="";else h="boolean"===c?!!h:h;return h}(d)}var ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ca(b,c,d,e){if(0<e){e=d+e-1;for(var f=0;f<b.length;++f){var g=b.charCodeAt(f);if(55296<=g&&57343>=g){var p=b.charCodeAt(++f);g=65536+((g&1023)<<10)|p&1023}if(127>=g){if(d>=e)break;c[d++]=g}else{if(2047>=g){if(d+1>=e)break;c[d++]=192|g>>6}else{if(65535>=g){if(d+2>=e)break;c[d++]=224|g>>12}else{if(d+3>=e)break;c[d++]=240|g>>18;c[d++]=128|g>>12&63}c[d++]=128|g>>6&63}c[d++]=128|g&63}}c[d]=0}}
function ia(b){for(var c=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:c+4}c+=1;d=N(c);ca(b,P,d,c);return d}var P,O,Q,R,ja=[],ka=[],la=[],ma=[],I=0;function na(){var b=a.preRun.shift();ja.unshift(b)}var T=0,U=null,V=null;a.preloadedImages={};a.preloadedAudios={};
function L(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";J(b);M=!0;b=new WebAssembly.RuntimeError(b+". Build with -s ASSERTIONS=1 for more info.");n(b);throw b;}function oa(){return W.startsWith("data:application/octet-stream;base64,")}var W;if(a.locateFile){if(W="main.wasm",!oa()){var pa=W;W=a.locateFile?a.locateFile(pa,B):B+pa}}else W=(new URL("main.wasm",import.meta.url)).toString();
function qa(){var b=W;try{if(b==W&&K)return new Uint8Array(K);if(E)return E(b);throw"both async and sync fetching of the wasm failed";}catch(c){L(c)}}
function ra(){if(!K&&(z||A)){if("function"==typeof fetch&&!W.startsWith("file://"))return fetch(W,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+W+"'";return b.arrayBuffer()}).catch(function(){return qa()});if(D)return new Promise(function(b,c){D(W,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return qa()})}
function X(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var d=c.j;"number"==typeof d?void 0===c.i?R.get(d)():R.get(d)(c.i):d(void 0===c.i?null:c.i)}}}var sa={};
(function(){function b(f){a.asm=f.exports;aa=a.asm.a;f=aa.buffer;a.HEAP8=P=new Int8Array(f);a.HEAP16=new Int16Array(f);a.HEAP32=Q=new Int32Array(f);a.HEAPU8=O=new Uint8Array(f);a.HEAPU16=new Uint16Array(f);a.HEAPU32=new Uint32Array(f);a.HEAPF32=new Float32Array(f);a.HEAPF64=new Float64Array(f);R=a.asm.e;ka.unshift(a.asm.b);T--;a.monitorRunDependencies&&a.monitorRunDependencies(T);0==T&&(null!==U&&(clearInterval(U),U=null),V&&(f=V,V=null,f()))}function c(f){b(f.instance)}function d(f){return ra().then(function(g){return WebAssembly.instantiate(g,
e)}).then(function(g){return g}).then(f,function(g){J("failed to asynchronously prepare wasm: "+g);L(g)})}var e={a:sa};T++;a.monitorRunDependencies&&a.monitorRunDependencies(T);if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(f){return J("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return K||"function"!=typeof WebAssembly.instantiateStreaming||oa()||W.startsWith("file://")||"function"!=typeof fetch?d(c):fetch(W,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
e).then(c,function(g){J("wasm streaming compile failed: "+g);J("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(n);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.b).apply(null,arguments)};a._resize=function(){return(a._resize=a.asm.c).apply(null,arguments)};a._main=function(){return(a._main=a.asm.d).apply(null,arguments)};
var da=a.stackSave=function(){return(da=a.stackSave=a.asm.f).apply(null,arguments)},ea=a.stackRestore=function(){return(ea=a.stackRestore=a.asm.g).apply(null,arguments)},N=a.stackAlloc=function(){return(N=a.stackAlloc=a.asm.h).apply(null,arguments)};a.cwrap=function(b,c,d,e){d=d||[];var f=d.every(function(g){return"number"===g});return"string"!==c&&f&&!e?a["_"+b]:function(){return ba(b,c,d,arguments)}};var Y;
function H(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}V=function ta(){Y||Z();Y||(V=ta)};
function Z(b){function c(){if(!Y&&(Y=!0,a.calledRun=!0,!M)){X(ka);X(la);m(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(ua){var d=b,e=a._main;d=d||[];var f=d.length+1,g=N(4*(f+1));Q[g>>2]=ia(x);for(var p=1;p<f;p++)Q[(g>>2)+p]=ia(d[p-1]);Q[(g>>2)+f]=0;try{var q=e(f,g);if(!(noExitRuntime||0<I)){if(a.onExit)a.onExit(q);M=!0}y(q,new H(q))}catch(v){v instanceof H||"unwind"==v||y(1,v)}finally{}}if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;)d=a.postRun.shift(),
ma.unshift(d);X(ma)}}b=b||u;if(!(0<T)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)na();X(ja);0<T||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c())}}a.run=Z;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();var ua=!0;a.noInitialRun&&(ua=!1);Z();


  return Module.ready
}
);
})();
export default Module;